repository_type: pipeline

nf_core_version: 4.1.0

lint:
  files_unchanged:
    - docs/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - LICENSE
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-tso500_v2_reference_preparation_logo_light.png
    - docs/images/nf-core-tso500_v2_reference_preparation_logo_light.png
    - docs/images/nf-core-tso500_v2_reference_preparation_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/pr-comment.yml
    - .github/workflows/linting.yml
    - .github/.dockstore.yml
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config: false
  files_exist:
    - CHANGELOG.md
    - assets/multiqc_config.yml
    - LICENSE
    - CITATIONS.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-tso500_v2_reference_preparation_logo_light.png
    - docs/images/nf-core-tso500_v2_reference_preparation_logo_light.png
    - docs/images/nf-core-tso500_v2_reference_preparation_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/.dockstore.yml
    - docs/CONTRIBUTING.md
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/pr-comment.yml
    - .github/workflows/linting.yml
  readme:
    - nextflow_badge
    - nfcore_template_badge
    - nextflow_badge

template:
  org: inpred
  name: tso500_v2_reference_preparation
  description: nextflow workflow to prepare reference files (PON) for tso500_v2_post_processing
  author: "@marrip"
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - github
    - github_badges
    - changelog
    - license
    - ci
    - igenomes
    - multiqc
    - seqera_platform
    - gpu
    - codespaces
    - vscode
    - citations
    - rocrate
    - email
  is_nfcore: false
