name: test_stub
on:
  push:
  pull_request:

jobs:
  nextflow:
    runs-on: ubuntu-latest
    container:
      image: nextflow/nextflow:26.04.6
      options: --user root
    steps:
      - name: Install tar
        run: yum install -y tar gzip
      - name: Check out pipeline code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Stubbing
        run: nextflow run . -stub-run -profile test_stub